//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MP3Player.cpp
//  @ Date : 20.09.2017
//  @ Author : 
//
//


#include "MP3Player.h"

void MP3Player::Регулирование(int громкости) {

}

void MP3Player::Переключение(int песни) {

}

void MP3Player::Включить() {

}

void MP3Player::Выключить() {

}

void MP3Player::Прослушивание(int музыки) {

}

